version: "3.8"

services:
  comfy:
    build: .
    image: masamunet/comfyui-hunyuanvideo:latest
    ports:
      - "8888:8888"
      - "8188:8188"
    volumes:
      - ./models:/workspace/ComfyUI/models
      - ./output:/workspace/ComfyUI/output
      - ./notebooks:/workspace/notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        if [ ! -f /workspace/ComfyUI/models/.downloaded ]; then
          mkdir -p /workspace/ComfyUI/models/clip /workspace/ComfyUI/models/vae /workspace/ComfyUI/models/loras /workspace/ComfyUI/models/checkpoints /workspace/ComfyUI/models/text_encoders /workspace/ComfyUI/models/unet /workspace/ComfyUI/models/controlnet /workspace/ComfyUI/models/upscale_models /workspace/ComfyUI/models/diffusion_models /workspace/ComfyUI/models/LLM
          
          wget -nc -P /workspace/ComfyUI/models/clip https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/clip_l.safetensors
          wget -nc -P /workspace/ComfyUI/models/clip https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp16.safetensors
          wget -nc -P /workspace/ComfyUI/models/clip https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp8_e4m3fn.safetensors
          
          wget -nc -P /workspace/ComfyUI/models/vae https://huggingface.co/Kijai/HunyuanVideo_comfy/resolve/main/hunyuan_video_vae_bf16.safetensors
          wget -nc -P /workspace/ComfyUI/models/diffusion_models https://huggingface.co/Kijai/HunyuanVideo_comfy/resolve/main/hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors
          
          touch /workspace/ComfyUI/models/.downloaded
        fi
        python main.py --listen
