version: "3.8"

services:
  comfy:
    build: .
    ports:
      - "8188:8188"
    volumes:
      - ./models:/app/models
      - ./output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        if [ ! -f /app/models/.downloaded ]; then
          mkdir -p /app/models/clip /app/models/vae /app/models/loras /app/models/checkpoints /app/models/text_encoders /app/models/unet /app/models/controlnet /app/models/upscale_models /app/models/diffusion_models /app/models/LLM
          
          wget -nc -P /app/models/clip https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/clip_l.safetensors
          wget -nc -P /app/models/clip https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp16.safetensors
          wget -nc -P /app/models/clip https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp8_e4m3fn.safetensors
          
          wget -nc -P /app/models/vae https://huggingface.co/Kijai/HunyuanVideo_comfy/resolve/main/hunyuan_video_vae_bf16.safetensors
          wget -nc -P /app/models/diffusion_models https://huggingface.co/Kijai/HunyuanVideo_comfy/resolve/main/hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors
          
          touch /app/models/.downloaded
        fi
        python main.py
